version: '3.8'

services:
  nexts3:
    build: .
    container_name: nexts3
    ports:
      - "3060:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_S3_ENDPOINT=${NEXT_PUBLIC_S3_ENDPOINT}
      - NEXT_PUBLIC_S3_ACCESS_KEY=${NEXT_PUBLIC_S3_ACCESS_KEY}
      - NEXT_PUBLIC_S3_SECRET_KEY=${NEXT_PUBLIC_S3_SECRET_KEY}
      - NEXT_PUBLIC_S3_REGION=${NEXT_PUBLIC_S3_REGION}
      - NEXT_PUBLIC_S3_BUCKET=${NEXT_PUBLIC_S3_BUCKET}
      - CODE=${CODE}
    restart: unless-stopped
    networks:
      - nexts3_network

networks:
  nexts3_network:
    driver: bridge 