# 使用 Node.js 官方镜像作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制所有源代码
COPY . .

# 设置构建时的环境变量
ARG NEXT_PUBLIC_S3_ENDPOINT
ARG NEXT_PUBLIC_S3_ACCESS_KEY
ARG NEXT_PUBLIC_S3_SECRET_KEY
ARG NEXT_PUBLIC_S3_REGION
ARG NEXT_PUBLIC_S3_BUCKET
ARG CODE

ENV NEXT_PUBLIC_S3_ENDPOINT=${NEXT_PUBLIC_S3_ENDPOINT}
ENV NEXT_PUBLIC_S3_ACCESS_KEY=${NEXT_PUBLIC_S3_ACCESS_KEY}
ENV NEXT_PUBLIC_S3_SECRET_KEY=${NEXT_PUBLIC_S3_SECRET_KEY}
ENV NEXT_PUBLIC_S3_REGION=${NEXT_PUBLIC_S3_REGION}
ENV NEXT_PUBLIC_S3_BUCKET=${NEXT_PUBLIC_S3_BUCKET}
ENV CODE=${CODE}

# 构建应用
RUN npm run build

# 暴露端口
EXPOSE 3060

# 启动应用
CMD ["npm", "start"] 